server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    schema: auth
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: auth
  flyway:
    schemas: auth
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: bG9uZ3NlY3VyZWhpZ2hzZWNyZXRrZXlmb3Jqc29ud2ViYXBwbGljYXRpb25zMTIz
  expirationTime: 86400000